project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: "https://nadhira.me" # you must change this appropriately for RSS feeds to work properly
  title: ""
  navbar:
    background: light
    search: true
    pinned: true
    tools:
      - icon: github
        href: https://github.com/azzahrandhr
    left:
      - text: "About"
        href: "#about"
      - text: "Interests"
        href: "#interests"
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full


  